# Generated by Django 5.2.1 on 2025-06-17 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timestamo',
            new_name='timestamp',
        ),
    ]
